/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY.
 *
 * This checksum is generated from all the files in the `__generated__` directory that are
 * also part of the `syncManager` file, and any dependency they might have (eg. fragments).
 */

export const relayChecksum = "a901c1e6e722df2ff91f92849794c2119919491d" // pragma: allowlist secret
