/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY.
 *
 * This checksum is generated from all the files in the `__generated__` directory that are
 * also part of the `syncManager` file, and any dependency they might have (eg. fragments).
 */

export const relayChecksum = "a7e65fda167e6b05e8b9fd94e53ef9522721d65c" // pragma: allowlist secret
