/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY.
 *
 * This checksum is generated from all the files in the `__generated__` directory that are
 * also part of the `syncManager` file, and any dependency they might have (eg. fragments).
 */

export const relayChecksum = "66632307f9011bf0f348b84ded8e93a6ef0058ef" // pragma: allowlist secret
