/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY.
 *
 * This checksum is generated from all the files in the `__generated__` directory that are
 * also part of the `syncManager` file, and any dependency they might have (eg. fragments).
 */

export const relayChecksum = "02271c99eabc13cccf8cc3eb01a8ee3002e9fa16" // pragma: allowlist secret
