/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY.
 *
 * This checksum is generated from all the files in the `__generated__` directory that are
 * also part of the `syncManager` file, and any dependency they might have (eg. fragments).
 */

export const relayChecksum = "d4c3a37f31ee65c4eb34a99d187b267e8fb0f6a8" // pragma: allowlist secret
