#!/usr/bin/env bash
set -euxo pipefail


source ./scripts/setup/export-release-vars
source ./scripts/ci/ci-setup-export-vars

# Check if there is a build in progress
echo "Checking if there is a build in progress..."
build_status=$(curl -s -H "Circle-Token: $CIRCLECI_TOKEN" https://circleci.com/api/v1.1/project/github/artsy/energy/tree/beta-ios | jq -r '.[0].status')

# Check if the build status is "running"
if [ "$build_status" = "running" ]; then
  echo "Another Android Build is running"
  read -p "There is a build currently running? Are you sure you want to overwrite it? (y/n) " -n 1 -r
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Proceeding with creating the beta..."
    git push origin "$LOCAL_BRANCH:beta-android" -f --no-verify
  else
    echo "Aborting..."
  fi
else
  echo "No other android is running. Proceeding with creating the beta..."
  git push origin "$LOCAL_BRANCH:beta-android" -f --no-verify
fi
