#!/usr/bin/env bash
set -euxo pipefail


./scripts/setup-fastlane-env
# brew not working in docker/linux in circleci
# brew update
# brew tap getsentry/tools
# brew install sentry-cli
if ! which sentry-cli;
then
  echo "installing sentry-cli"
  curl -sL https://sentry.io/get-cli/ | bash
else
  echo "sentry-cli already installed"
fi

bundle exec fastlane update_plugins

./scripts/setup-awscli

./scripts/setup-android-files
