#!/usr/bin/env bash
set -euxo pipefail

aws s3 cp s3://artsy-citadel/energy/energy-release.keystore android/app/release.keystore
aws s3 cp s3://artsy-citadel/energy/energy-android-secret.json android-secret.json
aws s3 cp s3://artsy-citadel/energy/energy-firebase-app-distribution.json energy-firebase-app-distribution.json
aws s3 cp s3://artsy-citadel/energy/energy-google-services.json android/app/google-services.json
