#!/usr/bin/env bash
set -euxo pipefail

./scripts/setup-fastlane-env
brew tap getsentry/tools
brew install sentry-cli
bundle exec fastlane update_plugins

./scripts/setup-awscli

# Android distribution
# aws s3 cp s3://artsy-citadel/eigen/GoogleService-Info.plist ios/Artsy/GoogleService-Info.plist
aws s3 cp s3://artsy-citadel/dev/energy-release.keystore android/app/release.keystore
aws s3 cp s3://artsy-citadel/dev/energy-android-secret.json android-secret.json
aws s3 cp s3://artsy-citadel/dev/energy-firebase-app-distribution.json energy-firebase-app-distribution.json
aws s3 cp s3://artsy-citadel/dev/energy-google-services.json android/app/google-services.json
