#!/usr/bin/env bash
set -euxo pipefail


./scripts/setup-fastlane-env
# brew not working in docker/linux in circleci
# brew update
# brew tap getsentry/tools
# brew install sentry-cli
if ! which sentry-cli;
then
  echo "installing sentry-cli"
  curl -sL https://sentry.io/get-cli/ | bash
else
  echo "sentry-cli already installed"
fi

bundle exec fastlane update_plugins

./scripts/setup-awscli

aws s3 cp s3://artsy-citadel/dev/energy-release.keystore android/app/release.keystore
aws s3 cp s3://artsy-citadel/dev/energy-android-secret.json android-secret.json
aws s3 cp s3://artsy-citadel/dev/energy-firebase-app-distribution.json energy-firebase-app-distribution.json
aws s3 cp s3://artsy-citadel/dev/energy-google-services.json android/app/google-services.json
