#!/usr/bin/env bash
set -euxo pipefail

./scripts/setup-fastlane-env
brew tap getsentry/tools
brew install sentry-cli
bundle exec fastlane update_plugins

./scripts/setup-awscli

# Android distribution
# aws s3 cp s3://artsy-citadel/eigen/GoogleService-Info.plist ios/Artsy/GoogleService-Info.plist
./scripts/setup-android-files

